import './style.css'
import * as THREE from 'three'
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js'
import {freshState,install,launch,pickup,tickDanger,type GameState} from './game-state'

const assetRoot='/assets/kenney-space-kit/'
const assets=['astronautA','rover','rock_crystalsLargeA','rock_crystalsLargeB','rocket_baseA','rocket_fuelA','rocket_sidesA','rocket_finsA','rocket_topA','terrain','terrain_roadStraight','terrain_roadCorner','craterLarge','rock_largeA','rock_largeB','turret_single','structure_detailed','hangar_smallA','satelliteDish_large','platform_large','gate_simple','machine_generator'] as const
type Asset=typeof assets[number]
const scene=new THREE.Scene();scene.background=new THREE.Color('#172735');scene.fog=new THREE.Fog('#172735',28,80)
const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,160)
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;document.querySelector('#game')!.append(renderer.domElement)
scene.add(new THREE.HemisphereLight('#bde6ef','#283642',2.2));const sun=new THREE.DirectionalLight('#ffd6ab',3.4);sun.position.set(-18,26,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun)
const clock=new THREE.Clock(),loader=new GLTFLoader(),models=new Map<Asset,THREE.Object3D>(),keys=new Set<string>()
let state:GameState=freshState(),paused=false,player=new THREE.Group(),rocket=new THREE.Group(),rocketParts:THREE.Object3D[]=[],cells:THREE.Object3D[]=[],turrets:THREE.Object3D[]=[],elapsed=0,boostHeat=0,boostLocked=false
const startPosition=new THREE.Vector3(0,0,2),cellPositions=[new THREE.Vector3(0,0,-8),new THREE.Vector3(12,0,-20),new THREE.Vector3(-12,0,-34)],rocketPosition=new THREE.Vector3(0,0,7)
const $=(selector:string)=>document.querySelector<HTMLElement>(selector)!
function clone(name:Asset,position:THREE.Vector3,scale=1){const object=models.get(name)!.clone(true);object.position.copy(position);object.scale.setScalar(scale);object.traverse(child=>{if(child instanceof THREE.Mesh){child.castShadow=true;child.receiveShadow=true}});scene.add(object);return object}

async function load(){await Promise.all(assets.map(async name=>{const gltf=await loader.loadAsync(`${assetRoot}${name}.glb`);models.set(name,gltf.scene);$('#load-status').textContent=`Loading Kenney assets · ${models.size}/${assets.length}`}));buildWorld();reset();$('#loading').hidden=true;$('#hud').hidden=false;animate()}
function buildWorld(){for(let z=-40;z<=10;z+=10)for(let x=-20;x<=20;x+=10)clone('terrain',new THREE.Vector3(x,-.35,z),10);for(let z=-33;z<=7;z+=5)clone('terrain_roadStraight',new THREE.Vector3(0,-.22,z),5);clone('platform_large',rocketPosition.clone().setY(-.1),4);clone('structure_detailed',new THREE.Vector3(-8,0,5),2.8);clone('hangar_smallA',new THREE.Vector3(9,0,-9),3.2);clone('satelliteDish_large',new THREE.Vector3(-10,0,-19),3);clone('craterLarge',new THREE.Vector3(9,-.1,-27),4);clone('machine_generator',new THREE.Vector3(7,0,5),2);[[-7,-13],[7,-23],[-6,-29],[6,-36]].forEach(([x,z],i)=>clone(i%2?'rock_largeB':'rock_largeA',new THREE.Vector3(x,0,z),2.4));turrets=[clone('turret_single',new THREE.Vector3(7,0,-25),2),clone('turret_single',new THREE.Vector3(-7,0,-32),2)];rocket.position.copy(rocketPosition);scene.add(rocket);for(const name of ['rocket_baseA','rocket_sidesA'] as Asset[]){const p=models.get(name)!.clone(true);p.scale.setScalar(2.3);rocket.add(p)}rocketParts=(['rocket_fuelA','rocket_finsA','rocket_topA'] as Asset[]).map((name,i)=>{const p=models.get(name)!.clone(true);p.scale.setScalar(2.3);p.position.y=i*.82;p.visible=false;rocket.add(p);return p});player.add(models.get('astronautA')!.clone(true));player.scale.setScalar(1.7);scene.add(player);clone('rover',new THREE.Vector3(3,0,1),2);cells=cellPositions.map((p,i)=>clone(i===1?'rock_crystalsLargeB':'rock_crystalsLargeA',p,2.2))}
function reset(){state=freshState();elapsed=0;boostHeat=0;boostLocked=false;paused=false;player.position.copy(startPosition);player.rotation.set(0,0,0);cells.forEach((cell,i)=>{cell.position.copy(cellPositions[i]);cell.visible=true});rocketParts.forEach(p=>p.visible=false);rocket.position.copy(rocketPosition);rocket.rotation.set(0,0,0);$('#terminal').hidden=true;$('#pause').hidden=true;updateHud()}
function nearbyCell(){return cells.findIndex((cell,i)=>!state.collected[i]&&cell.position.distanceTo(player.position)<2.8)}
function interact(){if(state.phase!=='playing')return;const cell=nearbyCell();if(cell>=0&&state.carrying===null){state=pickup(state,cell);cells[cell].visible=false;chirp(620);updateHud();return}if(state.carrying!==null&&player.position.distanceTo(rocketPosition)<4){state=install(state);rocketParts[state.installed-1].visible=true;chirp(880);updateHud();return}if(state.installed===3&&player.position.distanceTo(rocketPosition)<4){state=launch(state);chirp(1100);finish()}}
function chirp(frequency:number){const ctx=new AudioContext(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=frequency;gain.gain.setValueAtTime(.045,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.12);osc.connect(gain).connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.13)}
function updateHud(){$('#cells').textContent=`${state.installed} / 3`;$('#shield').textContent=Math.ceil(state.shield).toString();$('#heat').textContent=boostLocked?'COOL':Math.ceil(boostHeat).toString();$('#timer-wrap').hidden=state.dustSeconds===null;$('#timer').textContent=Math.ceil(state.dustSeconds??60).toString();$('#objective').textContent=state.installed===3?'Return to the rocket and press E to launch':state.carrying!==null?'Deliver the signal cell to the rocket':`Recover signal cell ${state.installed+1}`}
function finish(){const success=state.phase==='completed';$('#terminal-tag').textContent=success?'MISSION COMPLETE':'SIGNAL LOST';$('#terminal-title').textContent=success?'Eos-7 is online':state.phase==='failed_timer'?'The dust front arrived':'Your shield collapsed';$('#terminal-copy').textContent=success?`Launch achieved in ${Math.max(1,Math.round(elapsed))} seconds. All three physical relay cells installed.`:'Press R to reset every system and try a safer route.';$('#terminal').hidden=false}
function move(dt:number){if(paused||state.phase!=='playing')return;const direction=new THREE.Vector3((keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),0,(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0));const wantsBoost=keys.has('ShiftLeft')||keys.has('ShiftRight');const boosting=wantsBoost&&!boostLocked&&direction.lengthSq()>0;if(boosting){boostHeat=Math.min(100,boostHeat+34*dt);if(boostHeat>=100)boostLocked=true}else{boostHeat=Math.max(0,boostHeat-22*dt);if(boostLocked&&boostHeat<=18)boostLocked=false}if(direction.lengthSq()){direction.normalize();const speed=boosting?9:4.2;player.position.addScaledVector(direction,speed*dt);player.position.x=THREE.MathUtils.clamp(player.position.x,-19,19);player.position.z=THREE.MathUtils.clamp(player.position.z,-39,9);player.rotation.y=Math.atan2(direction.x,direction.z);player.rotation.z=THREE.MathUtils.lerp(player.rotation.z,-direction.x*.12,.12)}else player.rotation.z*=.88;const inDanger=turrets.some(t=>t.position.distanceTo(player.position)<7);state=tickDanger(state,dt,inDanger?12*dt:0);if(state.phase!=='playing')finish()}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);if(!paused&&state.phase==='playing')elapsed+=dt;move(dt);cells.forEach((cell,i)=>{cell.rotation.y+=dt*.8;cell.position.y=cellPositions[i].y+.2+Math.sin(elapsed*2+i)*.16});if(state.phase==='completed'){rocket.position.y+=dt*2.5;rocket.rotation.y+=dt*.5}const target=new THREE.Vector3(player.position.x,player.position.y+10,player.position.z+13);camera.position.lerp(target,1-Math.pow(.001,dt));camera.lookAt(player.position.x,player.position.y+1,player.position.z-2);const cell=nearbyCell();let prompt='';if(cell>=0&&state.carrying===null)prompt='E · PICK UP SIGNAL CELL';else if(player.position.distanceTo(rocketPosition)<4&&state.carrying!==null)prompt='E · INSTALL CELL';else if(player.position.distanceTo(rocketPosition)<4&&state.installed===3)prompt='E · LAUNCH';$('#prompt').textContent=prompt;$('#prompt').classList.toggle('visible',Boolean(prompt));updateHud();renderer.render(scene,camera)}
addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='KeyE'&&!e.repeat)interact();if(e.code==='KeyR')reset();if(e.code==='Escape'){paused=!paused;$('#pause').hidden=!paused}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});$('#restart').addEventListener('click',reset)
Object.assign(window,{__EOS7__:{getState:()=>structuredClone(state),teleport:(x:number,z:number)=>player.position.set(x,0,z),interact,reset}})
load().catch(error=>{console.error(error);$('#load-status').textContent=`Asset load failed: ${error instanceof Error?error.message:String(error)}`})
